# Generated by Django 2.2.10 on 2022-01-06 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField(help_text='Add the original URL that you want to shorten.', verbose_name='Editable Key')),
                ('editable_key', models.CharField(blank=True, help_text='Add any random characters of your choice to shorten it.', max_length=255, null=True, unique=True)),
            ],
        ),
    ]
