# Generated by Django 2.2.10 on 2022-01-06 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='original_url',
            field=models.URLField(help_text='Add the original URL that you want to shorten.', verbose_name='Original Key'),
        ),
    ]
