# Generated by Django 2.2.10 on 2022-01-06 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortener', '0003_url_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='editable_key',
            field=models.CharField(blank=True, help_text='Add any random characters of your choice to shorten it.', max_length=255, null=True),
        ),
    ]
